main: net.tfminecraft.gathering.Gathering
api-version: '1.21.10'
name: Gathering
version: '${project.version}'
author: Drefvelin

depend: [TLibs, RPCharacters]
softdepend: [MMOCore]

commands:
  gathering:
    usage: /<command> <reload|clearcache|status|forcespawn|adminmode>
    description: Gathering admin commands
    permission: gathering.admin

permissions:
  gathering.admin:
    default: op
